site_name: Auspiow's note
site_url: https://auspiow.github.io/note/

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - rss:
      enabled: true
  - encryptcontent:
      password_inventory:
        secret: !ENV ENCRYPTCONTENT_PASSWORD
      threshold_warning_min_entropy: 0
nav:
  - Home: index.md
  - CTF:
      - Writeups:
        - AliyunCTF 2026: ctf/writeups/Aliyun2026.md
      - ZJUBus-Web: ctf/writeups/zjubus-web/index.md
  - CS:
      - Frontend:
        - JavaScript: cs/frontend/javascript.md

theme:
  name: material
  language: zh  # 设置为中文
  palette: 
    # 自动切换深浅模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-7
        help: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-4
        help: 切换到浅色模式
  features:
    - navigation.tabs      # 启用顶部导航栏
    - navigation.sections  # 侧边栏分组显示
    - search.suggest       # 搜索建议
    - search.highlight     # 搜索关键词高亮

markdown_extensions:
  - admonition          # 提示框
  - pymdownx.details    # 折叠框
  - pymdownx.highlight:
      pygments_style: one-dark
      pygments_lang_class: true
  - pymdownx.superfences # 支持代码块嵌套
  - pymdownx.tasklist:
      custom_checkbox: true
